spring.application.name=showcle-mvp-server

# SERVER INFO
server.address=localhost
server.port=8080

# MULTIPART
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

# UPLOAD PATH
server.file.storage-path=D://data/web/upload
server.file.web-path=/upload
spring.servlet.multipart.location=D://data/web/upload/temp

# MYBATIS CONFIG
mybatis.config-location=classpath:mybatis/config/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml

# DATA SOURCE
s
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/showcle_mvp?options=-c%20timezone=Asia/Seoul
spring.datasource.username=showcle
spring.datasource.password=showcle

# LOGGING
logging.level.org.springframework=DEBUG
logging.level.com.showcle=DEBUG
logging.level.java.sql=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

# SESSION TIMEOUT ( EMBED TOMCAT )
server.servlet.session.timeout=120m

# CORS SETTING
server.cors.allowed-origins=http://localhost:8080
server.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
server.cors.allowed-header=*

# SCHEDULER
scheduler.carry.over.active=false
