-- ============================================================
-- 회원 정보 조회
-- ============================================================
create table showcle_member
(
    idx           bigint generated by default as identity,
    email         varchar(100) not null,
    passwd        varchar(200) not null,
    name          varchar(20)  not null,
    country_code  varchar(10)  not null,
    phone         varchar(20)  not null,
    device        varchar(1),
    push_token    varchar(512),
    profile_img   bigint,
    push_yn       smallint default 0,
    last_login_dt timestamp,
    discarded     smallint default 0,
    created_at    timestamp,
    created_by    varchar(100),
    updated_at    timestamp,
    updated_by    varchar(100),
    primary key(idx)
);

comment on table showcle_member is '회원 정보';
comment on column showcle_member.idx is '일련번호';
comment on column showcle_member.email is '이메일';
comment on column showcle_member.passwd is '비밀번호';
comment on column showcle_member.name is '이름';
comment on column showcle_member.country_code is '국가 코드';
comment on column showcle_member.phone is '전화번호';
comment on column showcle_member.device is 'a: 안드로이드, i: ios, w: 웹 (?)';
comment on column showcle_member.push_token is '푸시 토큰';
comment on column showcle_member.profile_img is '프로필 이미지 파일 idx';
comment on column showcle_member.push_yn is '푸시 발송 여부';
comment on column showcle_member.last_login_dt is '최종 로그인 일시';
comment on column showcle_member.discarded is '삭제 여부';
comment on column showcle_member.created_at is '등록일시';
comment on column showcle_member.created_by is '생성자';
comment on column showcle_member.updated_at is '등록일시';
comment on column showcle_member.updated_by is '수정자';


-- ============================================================
-- 회원 인증 메일 발송 이력
-- ============================================================
create table showcle_member_mail_auth
(
    idx           bigint generated by default as identity,
    email         varchar(100) not null,
    code          varchar(4) not null,
    send_dt     timestamp,
    auth_dt     timestamp,
    expired_dt  timestamp,
    primary key(idx)
);

comment on table showcle_member_mail_auth is '회원 인증 메일 발송이력';
comment on column showcle_member_mail_auth.idx is '일련번호';
comment on column showcle_member_mail_auth.email is '인증 요청 이메일';
comment on column showcle_member_mail_auth.code is '발송 코드';
comment on column showcle_member_mail_auth.send_dt is '발송 일시';
comment on column showcle_member_mail_auth.auth_dt is '인증 완료일시';
comment on column showcle_member_mail_auth.expired_dt is '인증번호 만료일시';


-- ============================================================
-- 첨부파일 공통 테이블
-- ============================================================
create table showcle_file
(
    idx	bigint generated by default as identity,
    owner_idx bigint not null,
    type varchar(30) not null,
    file_type varchar(50),
    file_size varchar(200),
    save_file_name varchar(200),
    real_file_name varchar(200),
    save_path varchar(200),
    web_path varchar(200),
    file_key varchar(200),
    discarded smallint default 0,
    created_at timestamp,
    created_by varchar(100),
    primary key(idx)
);

create index showcle_file_owner_idx on showcle_file(owner_idx);
create index showcle_file_type on showcle_file(type);

comment on table showcle_file is '첨부파일';
comment on column showcle_file.idx is '일련번호';
comment on column showcle_file.owner_idx is '파일 소유권자';
comment on column showcle_file.type is '업로드 파일 타입';
comment on column showcle_file.file_type is '파일 MIME TYPE';
comment on column showcle_file.file_size is '파일 용량';
comment on column showcle_file.save_file_name is '저장 파일명';
comment on column showcle_file.real_file_name is '실제 파일명';
comment on column showcle_file.save_path is '저장 경로';
comment on column showcle_file.web_path is '웹 접근 경로';
comment on column showcle_file.file_key is '파일 다운로드 키';
comment on column showcle_file.discarded is '삭제 여부';
comment on column showcle_file.created_at is '등록일시';
comment on column showcle_file.created_by is '등록자';

