-- ============================================================
-- 회원 정보 조회
-- ============================================================
create table showcle_member
(
    idx           bigint generated by default as identity,
    email         varchar(100) not null,
    passwd        varchar(200) not null,
    name          varchar(20)  not null,
    grade         smallint default 0,
    country_code  varchar(10)  not null,
    phone         varchar(20)  not null,
    device        varchar(1),
    push_token    varchar(512),
    profile_img   bigint,
    push_yn       smallint default 0,
    last_login_dt timestamp,
    discarded     smallint default 0,
    created_at    timestamp,
    created_by    varchar(100),
    updated_at    timestamp,
    updated_by    varchar(100),
    primary key(idx)
);

comment on table showcle_member is '회원 정보';
comment on column showcle_member.idx is '일련번호';
comment on column showcle_member.email is '이메일';
comment on column showcle_member.passwd is '비밀번호';
comment on column showcle_member.name is '이름';
comment on column showcle_member.grade is '등급';
comment on column showcle_member.country_code is '국가 코드';
comment on column showcle_member.phone is '전화번호';
comment on column showcle_member.device is 'a: 안드로이드, i: ios, w: 웹 (?)';
comment on column showcle_member.push_token is '푸시 토큰';
comment on column showcle_member.profile_img is '프로필 이미지 파일 idx';
comment on column showcle_member.push_yn is '푸시 발송 여부';
comment on column showcle_member.last_login_dt is '최종 로그인 일시';
comment on column showcle_member.discarded is '삭제 여부';
comment on column showcle_member.created_at is '등록일시';
comment on column showcle_member.created_by is '생성자';
comment on column showcle_member.updated_at is '등록일시';
comment on column showcle_member.updated_by is '수정자';


-- ============================================================
-- 회원 인증 메일 발송 이력
-- ============================================================
create table showcle_member_mail_auth
(
    idx           bigint generated by default as identity,
    email         varchar(100) not null,
    code          varchar(4) not null,
    send_dt     timestamp,
    auth_dt     timestamp,
    expired_dt  timestamp,
    primary key(idx)
);

comment on table showcle_member_mail_auth is '회원 인증 메일 발송이력';
comment on column showcle_member_mail_auth.idx is '일련번호';
comment on column showcle_member_mail_auth.email is '인증 요청 이메일';
comment on column showcle_member_mail_auth.code is '발송 코드';
comment on column showcle_member_mail_auth.send_dt is '발송 일시';
comment on column showcle_member_mail_auth.auth_dt is '인증 완료일시';
comment on column showcle_member_mail_auth.expired_dt is '인증번호 만료일시';


-- ============================================================
-- 회원 SNS 연동 테이블
-- ============================================================
CREATE TABLE showcle_member_social (
    idx bigint generated by default as identity,
    member_idx bigint not null,
    provider varchar(20) not null,
    provider_user_id varchar(255) not null,
    email varchar(100),
    created_at timestamp,
    primary key (idx)
);

comment on table showcle_member_social is 'SNS 연동 정보 테이블';
comment on column showcle_member_social.idx is '일련번호';
comment on column showcle_member_social.member_idx is 'SNS 연동 회원 idx';
comment on column showcle_member_social.provider is 'SNS 연동 provider ( GOOGLE, KAKAO, APPLE )';
comment on column showcle_member_social.provider_user_id is 'provider 별 sns 고유 id';
comment on column showcle_member_social.email is '이메일';
comment on column showcle_member_social.created_at is '생성일시';

create index showcle_member_social_idx on showcle_member_social(provider, provider_user_id);


-- ============================================================
-- 첨부파일 공통 테이블
-- ============================================================
create table showcle_file
(
    idx	bigint generated by default as identity,
    owner_idx bigint not null,
    type varchar(30) not null,
    file_type varchar(50),
    file_size varchar(200),
    save_file_name varchar(200),
    real_file_name varchar(200),
    save_path varchar(200),
    web_path varchar(200),
    file_key varchar(200),
    discarded smallint default 0,
    created_at timestamp,
    created_by varchar(100),
    primary key(idx)
);

create index showcle_file_owner_idx on showcle_file(owner_idx);
create index showcle_file_type on showcle_file(type);

comment on table showcle_file is '첨부파일';
comment on column showcle_file.idx is '일련번호';
comment on column showcle_file.owner_idx is '파일 소유권자';
comment on column showcle_file.type is '업로드 파일 타입';
comment on column showcle_file.file_type is '파일 MIME TYPE';
comment on column showcle_file.file_size is '파일 용량';
comment on column showcle_file.save_file_name is '저장 파일명';
comment on column showcle_file.real_file_name is '실제 파일명';
comment on column showcle_file.save_path is '저장 경로';
comment on column showcle_file.web_path is '웹 접근 경로';
comment on column showcle_file.file_key is '파일 다운로드 키';
comment on column showcle_file.discarded is '삭제 여부';
comment on column showcle_file.created_at is '등록일시';
comment on column showcle_file.created_by is '등록자';


-- ============================================================
-- 국가 코드
-- ============================================================
create table showcle_country_code
(
    idx	bigint generated by default as identity,
    code varchar(10) not null,
    name varchar(100),
    original_name varchar(100),
    order_by int default 0,
    primary key(idx)
);

comment on table showcle_country_code is '국가 코드';
comment on column showcle_country_code.idx is '일련번호';
comment on column showcle_country_code.code is '국가코드';
comment on column showcle_country_code.name is '국가명 (한글)';
comment on column showcle_country_code.original_name is '국가명 (원어)';
comment on column showcle_country_code.order_by is '정렬 순서';

insert into showcle_country_code(name, original_name, code, order_by) values ('그리스','Ελλάδα','+30', 1);
insert into showcle_country_code(name, original_name, code, order_by) values ('남아프리카 공화국','Republiek van Suid-Afrika','+27', 2);
insert into showcle_country_code(name, original_name, code, order_by) values ('네덜란드','Nederland','+31', 3);
insert into showcle_country_code(name, original_name, code, order_by) values ('네팔','नेपाल','+977', 4);
insert into showcle_country_code(name, original_name, code, order_by) values ('노르웨이','Norge','+47', 5);
insert into showcle_country_code(name, original_name, code, order_by) values ('대만','台灣','+886', 6);
insert into showcle_country_code(name, original_name, code, order_by) values ('대한민국','대한민국','+82', 7);
insert into showcle_country_code(name, original_name, code, order_by) values ('덴마크','Danmark','+45', 8);
insert into showcle_country_code(name, original_name, code, order_by) values ('독일','Deutschland','+49', 9);
insert into showcle_country_code(name, original_name, code, order_by) values ('러시아','Россия','+7', 10);
insert into showcle_country_code(name, original_name, code, order_by) values ('말레이시아','Malaysia','+60', 11);
insert into showcle_country_code(name, original_name, code, order_by) values ('미국','USA','+1', 12);
insert into showcle_country_code(name, original_name, code, order_by) values ('방글라데시','বাংলাদেশ','+880', 13);
insert into showcle_country_code(name, original_name, code, order_by) values ('베트남','Việt Nam','+84', 14);
insert into showcle_country_code(name, original_name, code, order_by) values ('불가리아','България','+359', 15);
insert into showcle_country_code(name, original_name, code, order_by) values ('브라질','Brasil','+55', 16);
insert into showcle_country_code(name, original_name, code, order_by) values ('세르비아','Србија','+381', 17);
insert into showcle_country_code(name, original_name, code, order_by) values ('스리랑카','ශ්‍රී ලංකාව','+94', 18);
insert into showcle_country_code(name, original_name, code, order_by) values ('스웨덴','Sverige','+46', 19);
insert into showcle_country_code(name, original_name, code, order_by) values ('스페인','España','+34', 20);
insert into showcle_country_code(name, original_name, code, order_by) values ('슬로바키아','Slovensko','+421', 21);
insert into showcle_country_code(name, original_name, code, order_by) values ('영국','UK','+44', 22);
insert into showcle_country_code(name, original_name, code, order_by) values ('우크라이나','Україна','+380', 23);
insert into showcle_country_code(name, original_name, code, order_by) values ('이탈리아','Italia','+39', 24);
insert into showcle_country_code(name, original_name, code, order_by) values ('인도','भारत','+91', 25);
insert into showcle_country_code(name, original_name, code, order_by) values ('인도네시아','Indonesia','+62', 26);
insert into showcle_country_code(name, original_name, code, order_by) values ('일본','日本','+81', 27);
insert into showcle_country_code(name, original_name, code, order_by) values ('체코','Česká republika','+420', 28);
insert into showcle_country_code(name, original_name, code, order_by) values ('캐나다','Canada','+1', 29);
insert into showcle_country_code(name, original_name, code, order_by) values ('크로아티아','Hrvatska','+385', 30);
insert into showcle_country_code(name, original_name, code, order_by) values ('태국','ประเทศไทย','+66', 31);
insert into showcle_country_code(name, original_name, code, order_by) values ('터키','Türkiye','+90', 32);
insert into showcle_country_code(name, original_name, code, order_by) values ('포르투갈','Portugal','+351', 33);
insert into showcle_country_code(name, original_name, code, order_by) values ('폴란드','Polska','+48', 34);
insert into showcle_country_code(name, original_name, code, order_by) values ('프랑스','France','+33', 35);
insert into showcle_country_code(name, original_name, code, order_by) values ('핀란드','Suomi','+358', 36);
insert into showcle_country_code(name, original_name, code, order_by) values ('필리핀','Pilipinas','+63', 37);
insert into showcle_country_code(name, original_name, code, order_by) values ('헝가리','Magyarország','+36', 38);
insert into showcle_country_code(name, original_name, code, order_by) values ('홍콩','香港','+852', 39);